-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 11:24:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ci
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ci` ;

-- -----------------------------------------------------
-- Schema ci
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ci` DEFAULT CHARACTER SET utf8 ;
USE `ci` ;

-- -----------------------------------------------------
-- Table `ci`.`build`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ci`.`build` ;

CREATE TABLE IF NOT EXISTS `ci`.`build` (
  `build_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `branch` VARCHAR(100) NOT NULL,
  `elapsed` DOUBLE NULL,
  `number_passed` INT NULL,
  `number_failed` INT NULL,
  PRIMARY KEY (`build_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ci`.`passedTest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ci`.`passedTest` ;

CREATE TABLE IF NOT EXISTS `ci`.`passedTest` (
  `passed_id` INT NOT NULL AUTO_INCREMENT,
  `build_id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`passed_id`),
  INDEX `fk_table1_Build_idx` (`build_id` ASC),
  CONSTRAINT `fk_table1_Build`
    FOREIGN KEY (`build_id`)
    REFERENCES `ci`.`build` (`build_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ci`.`failedTest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ci`.`failedTest` ;

CREATE TABLE IF NOT EXISTS `ci`.`failedTest` (
  `failed_id` INT NOT NULL AUTO_INCREMENT,
  `build_id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`failed_id`),
  INDEX `fk_FailedTest_Build1_idx` (`build_id` ASC),
  CONSTRAINT `fk_FailedTest_Build1`
    FOREIGN KEY (`build_id`)
    REFERENCES `ci`.`build` (`build_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
