name: slack_notification

on: [push]

jobs:
  notification:
    
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'New commit'
        SLACK_MESSAGE: 'A new commit has been pushed'
